# Generated by Django 3.2.20 on 2024-09-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Event_Image', models.ImageField(default='', upload_to='media/Event/images')),
                ('Event_Name', models.CharField(max_length=2000)),
                ('Event_Venue', models.TextField()),
                ('Organizer_Name', models.CharField(max_length=200)),
                ('Organizer_Phone', models.CharField(max_length=11)),
                ('Organizer_Email', models.EmailField(max_length=255)),
                ('Event_start', models.DateField()),
                ('Event_End', models.DateField(blank=True, null=True)),
                ('Event_Time', models.CharField(blank=True, max_length=255, null=True)),
                ('Event_Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('University_Image', models.ImageField(default='', upload_to='media/university/images')),
                ('University_Name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('About_University', models.TextField(default='')),
                ('Entry_Requirements', models.TextField(default='')),
                ('English_Requirements', models.TextField(default='')),
                ('Tuition_Fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Why_This_University', models.TextField(default='')),
                ('Available_Courses', models.ManyToManyField(related_name='universities', to='home.Available_Courses')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.country')),
            ],
        ),
        migrations.CreateModel(
            name='scholarships',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('university_Name', models.CharField(max_length=255)),
                ('scholarship', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default='', max_length=100)),
                ('scholarship_Name', models.CharField(max_length=1000)),
                ('Percentage', models.CharField(max_length=1000)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.country')),
            ],
        ),
        migrations.CreateModel(
            name='Pathways_Scholarships',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scholarship_Name', models.CharField(max_length=1000)),
                ('Percentage', models.CharField(max_length=1000)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.country')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=500)),
                ('Date_of_Birth', models.DateField()),
                ('phone_Number', models.CharField(max_length=11)),
                ('Interested', models.CharField(choices=[('Language Course', 'Language Course'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], default='', max_length=100)),
                ('Course_Title', models.CharField(max_length=1000)),
                ('Work_Experience', models.CharField(blank=True, max_length=255, null=True)),
                ('English_Test', models.CharField(choices=[('IELTS', 'IELTS'), ('UKVI IELTS', 'UKVI IELTS'), ('Pearson', 'Pearson'), ('TOEFL', 'TOEFL'), ('Other', 'Other'), ('No', 'No')], default='', max_length=100)),
                ('English_Test_Results', models.CharField(blank=True, max_length=300, null=True)),
                ('Message', models.TextField()),
                ('Study_Destination', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.country')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('image', models.ImageField(default=' ', upload_to='media/userimage')),
                ('name', models.CharField(max_length=255)),
                ('phone_Number', models.CharField(default='', max_length=11)),
                ('address', models.CharField(default='', max_length=300)),
                ('is_admin', models.BooleanField(default=False)),
                ('crtate_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
