# Generated by Django 3.2.20 on 2024-09-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Tuition_Fees',
            field=models.TextField(default=''),
        ),
    ]
