# Generated by Django 3.2.20 on 2024-09-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_university_tuition_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
