# Generated by Django 3.2.20 on 2024-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='Degree',
            field=models.ManyToManyField(related_name='universities', to='home.Degree'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
