# Generated by Django 3.2.20 on 2024-09-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240912_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Degree',
        ),
        migrations.AddField(
            model_name='university',
            name='degree',
            field=models.ManyToManyField(related_name='universities', to='home.degree'),
        ),
    ]
