# Generated by Django 3.2.20 on 2024-09-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240912_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Available_Courses',
        ),
        migrations.AddField(
            model_name='university',
            name='available_courses',
            field=models.ManyToManyField(related_name='universities', to='home.available_courses'),
        ),
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.ManyToManyField(related_name='universities', to='home.degree'),
        ),
    ]
