# Generated by Django 3.2.20 on 2024-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240913_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='available_courses',
            field=models.ManyToManyField(related_name='universities', to='home.available_courses'),
        ),
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.ManyToManyField(related_name='universities', to='home.degree'),
        ),
    ]
