# Generated by Django 4.2.7 on 2024-10-16 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20241006_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_time_slot',
            fields=[
                ('time', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=2000)),
                ('phone_Number', models.CharField(max_length=11)),
                ('Date', models.DateField()),
                ('Description', models.TextField()),
                ('Time', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.appointment_time_slot')),
                ('UserId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('degree', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.degree')),
            ],
        ),
    ]
