# Generated by Django 4.2.7 on 2024-10-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_appointment_time_slot_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Description',
        ),
    ]
